import React from "react";
import s from "./Box2.module.css"
import SimpleBar from 'simplebar-react';
import 'simplebar/dist/simplebar.min.css';


function Box1 () {
    return(
        <div className={s.wrap}>
            <div className={s.headingText}>Текст сообщения</div>
            <div className={s.scrollFlex} data-simplebar>
                <section  className={s.textScroll}> <SimpleBar className={s.text} >
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ullam fugit debitis cumque at aliquid ad sint? Velit voluptatum maxime cum? Provident odio asperiores corporis quas maxime? Nam magnam adipisci ipsam?
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. A, harum.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia, eius. Magnam minima aliquam laborum. Cupiditate debitis ducimus explicabo ab, sit beatae minima, ut sunt inventore libero id ea dolores expedita laboriosam itaque voluptatum sint reiciendis, aliquam quas esse. Amet aliquid, quidem perspiciatis sapiente obcaecati eveniet veritatis pariatur accusamus esse reiciendis distinctio at atque, nostrum ad quae architecto non maxime quos officiis hic? Recusandae impedit ipsam repudiandae. Reprehenderit non soluta mollitia veritatis eos deleniti laudantium praesentium, itaque, nihil et ut illo suscipit enim dolor, fugiat nobis accusamus libero voluptate. Voluptatem, velit harum? Distinctio vel eaque aut, excepturi accusantium ad ab nesciunt consequatur fugit odio provident aspernatur quam sed ut deleniti eum? Vero exercitationem iure nisi doloribus ab a eaque, quisquam ex doloremque non perspiciatis consectetur corporis quaerat, deserunt voluptatum amet maxime beatae reiciendis, ullam unde harum? Soluta dolores impedit quisquam amet quidem, cum excepturi nam. Molestias, ipsum labore eaque aliquid adipisci ad atque fugiat dolorem sequi quae similique ut rerum ipsa, quis, alias itaque sapiente error odio aliquam. Odio, eligendi fuga? Laboriosam fugiat veritatis tempora, in nobis accusamus earum optio accusantium doloribus ea voluptate quis et eos repudiandae provident officiis. Alias illum ad atque sed pariatur, hic facere suscipit modi aliquam!
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam nam provident vero harum tempora delectus eveniet molestias ipsam veniam aliquam neque, id assumenda nulla doloribus dicta quod placeat officiis, adipisci animi temporibus reiciendis explicabo est voluptatem laborum? Dolore, animi recusandae facere excepturi aliquid sunt soluta repellendus neque ipsa voluptatibus sit illo molestiae sequi, iusto numquam et eum minus asperiores quod incidunt suscipit quo labore. Excepturi, officia? Vitae nihil laboriosam nemo est aperiam magni libero iusto possimus ex magnam, facilis, veniam fugit minus. Temporibus, alias obcaecati. Veniam, quae molestias porro voluptates in ullam incidunt illo iste voluptatibus fugiat alias hic? Voluptatem repellendus ab, quaerat alias optio eum fuga cumque assumenda, consequuntur ipsum deleniti sed at, quisquam voluptates qui. Perferendis aperiam laudantium obcaecati excepturi esse dicta necessitatibus ut odit iusto architecto magni velit modi enim fugiat atque illo non, soluta quisquam dolorum in repudiandae ratione mollitia aliquam odio. Exercitationem impedit temporibus vel quis ut, recusandae illo necessitatibus consequuntur adipisci, accusamus quo aliquam eveniet culpa. Magni ratione nam nulla voluptas sed possimus non facilis debitis ex aut eos labore beatae, voluptatem, animi fugit? Dolor non laboriosam nemo officia repudiandae nam aspernatur exercitationem cupiditate, placeat sit voluptas numquam optio architecto explicabo veniam fugit atque velit! Nesciunt sint ipsum qui corrupti dicta! Ex natus perferendis porro nobis quam placeat non excepturi voluptatem temporibus, provident recusandae optio illo dolore mollitia tenetur possimus voluptates dolor error
                praesentium tempore a? Nam animi enim deleniti numquam eveniet laborum magnam alias, quos culpa reiciendis ut hic consequuntur magni laboriosam odit necessitatibus suscipit molestias sit eos? Sunt facilis, autem beatae dolorem debitis, maxime magnam obcaecati quod at odit eius. Est eveniet ab assumenda nisi itaque vel? Laboriosam voluptates fugit adipisci nulla aliquid nisi sit non, ab quam tempora quis, eos ipsa quae cumque? Quasi dolores fugit rem autem expedita provident, odit, atque nesciunt eligendi labore quidem cumque veniam asperiores modi est dignissimos sequi doloribus nostrum nihil! Doloremque incidunt necessitatibus mollitia eaque aperiam tempore praesentium non! Sit praesentium maiores nobis facilis mollitia? Adipisci necessitatibus aut, pariatur, totam exercitationem eius aliquid error at velit incidunt ad, quae sunt dignissimos nesciunt quaerat possimus accusantium quis et praesentium rem repellendus. Asperiores eos expedita quod consequuntur hic autem rem nisi illum soluta ullam facilis, pariatur corrupti harum dolorum doloribus minus, cum laudantium atque. Odio officia, corrupti, vitae facere similique dolorem, sed quam delectus illo corporis in minima fugiat? Saepe quasi voluptatum officia ducimus aliquam aut quam exercitationem, beatae facere voluptate tenetur ipsum illum molestias! Corporis neque suscipit expedita repellat inventore officia, recusandae aperiam, adipisci, non animi tempore! Odio dignissimos explicabo, molestias quas laudantium quam! Quo voluptate atque expedita quibusdam nobis mollitia, numquam voluptatibus dicta asperiores pariatur. Deleniti officiis autem eius provident labore deserunt obcaecati, tenetur eaque maxime? Nobis numquam, odio, deleniti ducimus 
                optio facilis dignissimos enim earum quisquam doloribus odit ut dolores porro sint omnis! Voluptate in deserunt cumque totam sequi molestiae blanditiis vero, qui numquam quas nesciunt molestias, asperiores a excepturi quam est quisquam voluptatem animi quis? Adipisci laboriosam et maxime accusantium ullam repellat id inventore culpa odit fugit iure earum voluptatum doloremque suscipit, officia quisquam veniam placeat assumenda iste, incidunt ipsum minus. Dolore corporis, delectus corrupti assumenda illum, rerum voluptatem nesciunt quidem mollitia suscipit dolorem dicta id eos sed vel, deleniti placeat! Nostrum accusamus, quis doloremque aperiam doloribus omnis dolorem. Minima molestiae cumque vero consequatur dolorem libero, dolores veniam quisquam commodi impedit tempore perspiciatis omnis consectetur dicta natus quod nostrum nulla inventore magnam enim ab suscipit unde quam. 
                Cumque expedita accusantium temporibus aperiam, ratione quasi. Dolores maiores nulla quae consectetur. Illum veritatis cum beatae harum minima ipsam quasi fugiat, praesentium sit vitae aliquam obcaecati quaerat doloribus. Sed sequi dicta corporis? Non rerum repudiandae sed voluptatibus perspiciatis, similique aspernatur suscipit quis, necessitatibus nulla doloremque possimus sit porro quae sunt amet libero! Assumenda architecto, incidunt optio, ullam autem ea quam tempora quaerat officia enim nemo! Laboriosam enim voluptate, maiores voluptas ad eveniet quos sit ut optio modi totam beatae aliquid rerum ratione mollitia recusandae, assumenda ipsam, eius eum quia provident eligendi. Hic est iure quidem nesciunt. Inventore, repellendus quisquam error laudantium quos cumque asperiores placeat eum aliquid voluptatem? Minus, quam exercitationem recusandae facere totam autem maiores aperiam libero tempore, nam voluptate rem nobis soluta ducimus officiis! Reiciendis quo rerum, corrupti officia qui dolor iure saepe cupiditate expedita atque natus numquam veritatis recusandae laudantium ipsum voluptate laboriosam adipisci! Porro officia unde delectus repellat enim iure id omnis sed ullam magnam, maiores, assumenda eligendi officiis atque labore nihil provident aspernatur libero rerum nulla neque maxime similique. Deserunt ratione cupiditate id quisquam magnam eum repudiandae dicta delectus aliquam, earum perspiciatis ipsum qui, laudantium molestias ex? Deserunt nemo ipsum provident minus quidem consequatur necessitatibus soluta minima sunt? Eveniet quod odit repudiandae! Placeat ratione, quae illo consequuntur deserunt earum magnam magni. Cum cupiditate nobis, repellendus temporibus, ab repellat modi, 
                obcaecati laborum nam quas nesciunt blanditiis vitae saepe repudiandae ratione maxime suscipit enim! Sequi illum aliquam saepe natus? Minus voluptate ratione quae! Quo dolores, sapiente harum laboriosam blanditiis officiis tenetur ex aut labore voluptates, exercitationem vitae. Reiciendis vero est laudantium voluptate labore dolorem ipsam placeat expedita minima eos totam eaque, perspiciatis sequi inventore odio earum autem natus officiis? Animi laboriosam possimus excepturi itaque soluta delectus, repellat, cumque vitae unde eligendi velit aspernatur officiis accusamus dignissimos a nulla beatae iure! Autem, unde quas! Possimus earum magnam sequi non cum accusantium odit vel quaerat alias maxime distinctio, maiores minus ullam a amet consectetur quae accusamus doloremque asperiores? Officiis obcaecati voluptas assumenda. Nulla dolor illo maxime, fugiat sapiente voluptate. Cum ad eos distinctio eum. Repellat similique corporis, fugiat tenetur est at iusto quam eos, suscipit cupiditate necessitatibus molestiae consectetur omnis? Alias, delectus aliquid. Assumenda nobis sapiente, placeat quia est rem aliquid at culpa consequatur provident nulla facilis reiciendis maiores quidem a debitis! Nisi, tempora aliquid sequi inventore aspernatur veritatis pariatur reiciendis doloribus voluptates id at fugit provident sunt eius. Molestias 
                possimus omnis obcaecati incidunt odio neque? Doloremque est soluta quo atque consequuntur dolor vel, repellendus placeat corporis ipsam, quos rerum sit dolorum quas minima necessitatibus!
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit distinctio ipsum obcaecati deserunt placeat iusto, sequi pariatur amet odit dicta molestias sit quisquam dolore recusandae quia quaerat perferendis. Incidunt, sunt. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem perspiciatis deserunt harum magni nostrum odio corporis. Aliquid maxime necessitatibus ad sequi nulla dolore totam temporibus minima praesentium, odio quasi beatae!</SimpleBar></section>
            </div>
        </div>
    );
}
export default Box1;